spring:
  config:
    name: Pract2
  datasource:
    url: jdbc:postgresql://localhost:5432/Jurnal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
  main:
    allow-circular-references: true
server:
  port: 8888